Repository DemienDrost/react-animotion, pull requests merged in 2023-10, with the labels that each got.

#19 Removed Interpolate from useAnimotionHelper
  src/hooks/useAnimotionHelpers.ts
Labels: hacktoberfest, hacktoberfest-accepted

#21 changed pageYOffset to scrollY
  src/components/StickyContainer/StickyContainer.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#20 create types.ts and add basic css keyframe and animation properties
  src/common/types.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#38 add easing functions to animotionOptions
  package-lock.json
  src/common/types.ts
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
